# docker-compose.yml

services:
  web:
    build: .
    container_name: litrevu_web
    command: gunicorn LITRevu.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      # Keep SQLite DB on host so it survives rebuilds
      - ./db.sqlite3:/app/db.sqlite3
